### ISSUE TITLE
Date parsing in unit tests picking up locale on users machine

### ISSUE THREAD

**Issue by FrankRay78** [Hilres/Hilres.TiingoApi#1]
Hello, firstly thank you for such a good repo and kindly sharing it. It saved me hours of work myself and the quality of your code is evident. 

Minor point, but felt it worth noting.  One of the unit tests is simply failing from the hard coded date in the InlineData attribute. eg:

        [Theory]
        [InlineData("msft", "3/4/2018", "3/4/2018", ResampleFrequency.Daily, 0)]
        [InlineData("msft", "3/5/2018", "3/5/2018", ResampleFrequency.Daily, 1)]
        [InlineData("msft", "3/5/2018", "3/9/2018", ResampleFrequency.Daily, 5)]
        [InlineData("msft", "12/31/2017", "2/28/2018", ResampleFrequency.Daily, 40)]
        [InlineData("msft", "12/31/2017", "2/28/2018", ResampleFrequency.Weekly, 10)]
        [InlineData("msft", "12/31/2017", "2/28/2018", ResampleFrequency.Monthly, 3)]
        [InlineData("msft", "12/31/2017", "2/28/2018", ResampleFrequency.Annually, 2)]
        [InlineData("ABT", "3/5/2018", "3/9/2018", ResampleFrequency.Daily, 5)]
        public async Task GetStockPrices_DateRange(string ticker, string startDate, string endDate, ResampleFrequency frequency, int count)
        {
            TiingoList<TiingoStockPrice> result = await this.service.GetStockPricesAsync(
                                                        ticker: ticker,
                                                        startDate: Parse.NullDateTime(startDate),
                                                        endDate: Parse.NullDateTime(endDate),
                                                        frequency: frequency);

            Assert.NotNull(result);

            Assert.True(result.ApiSuccessful);
            Assert.Equal(count, result.Count);
        }

The function works and pulls back data using my API key, but the test fails on the following Assert.Equal(count, result.Count);

I'm in the UK and if I switch around the Day / Month it starts passing so I can only think it's to do with how xUnit parses the dates.  Anyhow like I said not really a big deal.

Regards,
Frank

**Comment by FrankRay78** [comment]
It's occuring here FYI, the second TryParse override [not being used] explicitly takes a globalisation provider which would fix the issue I noted above.

        internal static DateTime? NullDateTime(string text)
        {
            return DateTime.TryParse(text, out DateTime date) ? (DateTime?)date : null;
        }

**Comment by danh955** [comment]
Thanks for the update.  I should look at the issue more often.  I applied your changes.

**Comment by FrankRay78** [comment]
Cool, thanks.  I had completely forgotten about this PR.

Regards,
Frank

*020 7097 7261** (UK)  | * ***@***.*** * | * Website
<http://www.frankray.net> * | * LinkedIn Profile
<https://uk.linkedin.com/in/frankray>
